// Initial blank employee object used to reset or initialize the employee form
export const initialEmployee = {
  e_id: "",
  first_name: "",
  middle_name: "",
  last_name: "",
  suffix: "",
  gender: "",
  birthday: "",
  phone_no: "",
  email: "",
  street_address: "",
  city: "",
  province: "",
  zip: "",
  department: "",
  project: "",
  team: "",
  position: "",
  employment: "",
  date_hired: "",
  base_monthly_pay: "",
  user_profile: "",
  pay_frequency: "",
  tax_id: "",
  sss_gsis_no: "",
  phic_id: "",
  hdmf_id: "",
  bank: "",
  bank_account: "",
};

// Fields that are required in the employee form before submission
export const requiredFields = [
  "e_id",
  "first_name",
  "last_name",
  "gender",
  "birthday",
  "phone_no",
  "email",
  "street_address",
  "city",
  "province",
  "zip",
  "department",
  "project",
  "team",
  "position",
  "employment",
  "date_hired",
  "base_monthly_pay",
  "user_profile",
  "pay_frequency",
  "tax_id",
  "sss_gsis_no",
  "phic_id",
  "hdmf_id",
  "bank",
  "bank_account",
];

// Dropdown options for selecting visible columns in the employee table
export const columnOptions = [
    { label: "Employee ID", value: "e_id" },
    { label: "Last Name", value: "last_name" },
    { label: "First Name", value: "first_name" },
    { label: "Middle Name", value: "middle_name" },
    { label: "Position", value: "position" },
    { label: "Province", value: "province" },
    { label: "City", value: "city" },
    { label: "Address", value: "address" },
    { label: "Postal Code", value: "postal_code" },
    { label: "Phone", value: "phone" },
    { label: "Email", value: "email" },
    { label: "Gender", value: "gender" },
    { label: "Birthday", value: "birthday" },
    { label: "SSS ID", value: "sss_id" },
    { label: "TIN", value: "tin" },
    { label: "PhilHealth ID", value: "philhealth_id" },
    { label: "PAG-IBIG ID", value: "pagibig_id" },
    { label: "Date Hired", value: "date_hired" },
    { label: "Salary", value: "salary" },
    { label: "Department", value: "department" }
  ];
